<?php
require 'includes/bootstrap.php';$id=(int)($_GET['id']??0);$orc=null;$itens=[];
if($id){$st=$pdo->prepare("SELECT * FROM orcamentos_orcamentos WHERE id=?");$st->execute([$id]);$orc=$st->fetch();if(!$orc)exit('Orçamento não encontrado.');$st=$pdo->prepare("SELECT * FROM orcamentos_itens WHERE orcamento_id=? ORDER BY ordem,id");$st->execute([$id]);$itens=$st->fetchAll();}
$clientes=$pdo->query("SELECT * FROM orcamentos_clientes WHERE ativo=1 ORDER BY nome")->fetchAll();$produtos=$pdo->query("SELECT * FROM orcamentos_produtos WHERE ativo=1 ORDER BY nome")->fetchAll();$servicos=$pdo->query("SELECT * FROM orcamentos_servicos WHERE ativo=1 ORDER BY nome")->fetchAll();require 'includes/header.php';?>
<div class="page-head"><h1><?= $id?'Editar':'Novo' ?> orçamento</h1></div><form class="card" method="post" action="orcamento_salvar.php"><input type="hidden" name="id" value="<?= $id ?>"><div class="form-grid"><div><label>Número</label><input readonly name="numero" value="<?= (int)($orc['numero']??proximoNumero($pdo)) ?>"></div><div><label>Data de emissão</label><input type="date" name="data_emissao" required value="<?= e($orc['data_emissao']??date('Y-m-d')) ?>"></div><div><label>Cliente *</label><select name="cliente_id" required><option value="">Selecione</option><?php foreach($clientes as $c):?><option value="<?= (int)$c['id'] ?>" <?= (($orc['cliente_id']??0)==$c['id'])?'selected':'' ?>><?= e($c['nome']) ?></option><?php endforeach;?></select></div><div><label>Título *</label><input name="titulo" required value="<?= e($orc['titulo']??'Proposta Comercial') ?>"></div><div><label>Validade (dias)</label><input type="number" min="1" name="validade_dias" value="<?= (int)($orc['validade_dias']??15) ?>"></div><div><label>Status</label><select name="status"><?php foreach(['rascunho','enviado','aprovado','recusado','cancelado'] as $s):?><option <?= (($orc['status']??'rascunho')===$s)?'selected':'' ?>><?= $s ?></option><?php endforeach;?></select></div></div>
<h3>Itens</h3><div id="itens"></div><button class="btn secondary" type="button" onclick="addItem()">+ Adicionar item</button><div class="form-grid" style="margin-top:18px"><div><label>Desconto (R$)</label><input type="number" step="0.01" min="0" name="desconto" value="<?= e((string)($orc['desconto']??'0.00')) ?>"></div><div><label>Prazo de entrega/execução</label><input name="prazo_entrega" value="<?= e($orc['prazo_entrega']??'') ?>"></div><div class="full"><label>Condições de pagamento</label><textarea name="condicoes_pagamento"><?= e($orc['condicoes_pagamento']??'') ?></textarea></div><div class="full"><label>Observações</label><textarea name="observacoes"><?= e($orc['observacoes']??'') ?></textarea></div></div><p><button class="btn success">Salvar orçamento</button></p></form>
<script>
const produtos=<?= json_encode($produtos,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>,servicos=<?= json_encode($servicos,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>,existentes=<?= json_encode($itens,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>;
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;')}function opts(t,s){let a=t==='produto'?produtos:servicos;return '<option value="">Item livre / selecionar...</option>'+a.map(x=>'<option value="'+x.id+'" '+(String(s)===String(x.id)?'selected':'')+'>'+esc(x.nome)+'</option>').join('')}
function addItem(d={tipo:'produto',referencia_id:'',descricao:'',detalhe:'',unidade:'un',quantidade:1,valor_unitario:0}){let i=document.querySelectorAll('.item-card').length,b=document.createElement('div');b.className='card item-card';b.style.marginBottom='10px';b.innerHTML='<div class="item-row"><select class="tipo" name="itens['+i+'][tipo]" onchange="trocaTipo(this)"><option value="produto" '+(d.tipo==='produto'?'selected':'')+'>Produto</option><option value="servico" '+(d.tipo==='servico'?'selected':'')+'>Serviço</option><option value="livre" '+(d.tipo==='livre'?'selected':'')+'>Livre</option></select><select class="ref" name="itens['+i+'][referencia_id]" onchange="preenche(this)">'+opts(d.tipo,d.referencia_id)+'</select><input name="itens['+i+'][quantidade]" type="number" min="0.001" step="0.001" value="'+esc(d.quantidade)+'"><input class="valor" name="itens['+i+'][valor_unitario]" type="number" min="0" step="0.01" value="'+esc(d.valor_unitario)+'"><button type="button" class="btn danger" onclick="this.closest(\'.item-card\').remove()">×</button></div><div class="form-grid"><div><label>Descrição</label><input class="desc" name="itens['+i+'][descricao]" required value="'+esc(d.descricao)+'"></div><div><label>Unidade</label><input class="un" name="itens['+i+'][unidade]" value="'+esc(d.unidade)+'"></div><div class="full"><label>Detalhe</label><textarea class="det" name="itens['+i+'][detalhe]">'+esc(d.detalhe)+'</textarea></div></div>';document.getElementById('itens').appendChild(b);if(d.tipo==='livre')b.querySelector('.ref').disabled=true;}
function trocaTipo(s){let c=s.closest('.item-card'),r=c.querySelector('.ref');r.innerHTML=opts(s.value,'');r.disabled=s.value==='livre';}function preenche(s){let c=s.closest('.item-card'),t=c.querySelector('.tipo').value,a=t==='produto'?produtos:servicos,x=a.find(v=>String(v.id)===String(s.value));if(!x)return;c.querySelector('.desc').value=x.nome;c.querySelector('.det').value=x.descricao||'';c.querySelector('.un').value=x.unidade||'un';c.querySelector('.valor').value=x.preco;}if(existentes.length)existentes.forEach(addItem);else addItem();
</script><?php require 'includes/footer.php';?>
