<?php
require 'includes/bootstrap.php';if($_SERVER['REQUEST_METHOD']!=='POST')redirect('orcamentos.php');
$id=(int)($_POST['id']??0);$numero=(int)($_POST['numero']??proximoNumero($pdo));$cliente=(int)($_POST['cliente_id']??0);$titulo=trim($_POST['titulo']??'');
if(!$cliente||!$titulo){flash('error','Cliente e título são obrigatórios.');redirect('orcamento_editar.php'.($id?'?id='.$id:''));}
$pdo->beginTransaction();try{$d=[$numero,$cliente,$titulo,$_POST['data_emissao']??date('Y-m-d'),(int)($_POST['validade_dias']??15),$_POST['status']??'rascunho',(float)($_POST['desconto']??0),trim($_POST['condicoes_pagamento']??''),trim($_POST['prazo_entrega']??''),trim($_POST['observacoes']??'')];
if($id){$pdo->prepare("UPDATE orcamentos SET numero=?,cliente_id=?,titulo=?,data_emissao=?,validade_dias=?,status=?,desconto=?,condicoes_pagamento=?,prazo_entrega=?,observacoes=? WHERE id=?")->execute([...$d,$id]);$pdo->prepare("DELETE FROM orcamento_itens WHERE orcamento_id=?")->execute([$id]);}
else{$pdo->prepare("INSERT INTO orcamentos(numero,cliente_id,titulo,data_emissao,validade_dias,status,desconto,condicoes_pagamento,prazo_entrega,observacoes) VALUES(?,?,?,?,?,?,?,?,?,?)")->execute($d);$id=(int)$pdo->lastInsertId();}
$st=$pdo->prepare("INSERT INTO orcamento_itens(orcamento_id,tipo,referencia_id,descricao,detalhe,unidade,quantidade,valor_unitario,ordem) VALUES(?,?,?,?,?,?,?,?,?)");$ord=0;foreach(($_POST['itens']??[]) as $i){$desc=trim($i['descricao']??'');if(!$desc)continue;$tipo=in_array($i['tipo']??'', ['produto','servico','livre'],true)?$i['tipo']:'livre';$ref=!empty($i['referencia_id'])?(int)$i['referencia_id']:null;$st->execute([$id,$tipo,$ref,$desc,trim($i['detalhe']??''),trim($i['unidade']??'un'),(float)($i['quantidade']??1),(float)($i['valor_unitario']??0),$ord++]);}$pdo->commit();flash('success','Orçamento salvo com sucesso.');redirect('orcamento_ver.php?id='.$id);}
catch(Throwable $e){$pdo->rollBack();flash('error','Erro ao salvar: '.$e->getMessage());redirect('orcamento_editar.php'.($id?'?id='.$id:''));}
