<?php
require_once __DIR__.'/bootstrap.php';
function orcamentoData(PDO $pdo,int $id):array{$st=$pdo->prepare("SELECT o.*,c.nome cliente,c.documento,c.contato,c.email cliente_email,c.telefone cliente_telefone,c.endereco cliente_endereco,c.cidade,c.uf FROM orcamentos_orcamentos o JOIN orcamentos_clientes c ON c.id=o.cliente_id WHERE o.id=?");$st->execute([$id]);$o=$st->fetch();if(!$o)throw new RuntimeException('Orçamento não encontrado.');$st=$pdo->prepare("SELECT * FROM orcamentos_itens WHERE orcamento_id=? ORDER BY ordem,id");$st->execute([$id]);$o['itens']=$st->fetchAll();$o['empresa']=configEmpresa($pdo);return $o;}
function logoDataUri(?string $path):string{if(!$path)return '';$full=dirname(__DIR__).'/'.$path;if(!is_file($full))return '';$mime=mime_content_type($full)?:'image/png';return 'data:'.$mime.';base64,'.base64_encode(file_get_contents($full));}
function renderOrcamento(array $o,bool $pdf=false):string{$e=$o['empresa'];$cor=$e['cor_primaria']??'#0b3a63';$logo=$pdf?logoDataUri($e['logo_path']??null):($e['logo_path']??'');$subtotal=0;foreach($o['itens'] as $i)$subtotal+=(float)$i['quantidade']*(float)$i['valor_unitario'];$total=max(0,$subtotal-(float)$o['desconto']);$validade=date('d/m/Y',strtotime($o['data_emissao'].' +'.(int)$o['validade_dias'].' days'));ob_start();?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><style>
@page{margin:24mm 16mm 22mm}body{font-family:DejaVu Sans,Arial,sans-serif;color:#263746;font-size:10.5pt;margin:0}.head{border-bottom:3px solid <?= e($cor) ?>;padding-bottom:12px;margin-bottom:20px}.head table{width:100%;border-collapse:collapse}.logo{max-width:170px;max-height:70px}.empresa{text-align:right;font-size:9pt;color:#536573}.titulo{color:<?= e($cor) ?>;font-size:22pt;margin:10px 0 3px}.numero{color:#687985}.intro{background:#f3f7fa;border-left:4px solid <?= e($cor) ?>;padding:12px 14px;margin:18px 0;line-height:1.55}.box{border:1px solid #d9e1e7;padding:12px 14px;margin:12px 0}.box h3{margin:0 0 8px;color:<?= e($cor) ?>}.items{width:100%;border-collapse:collapse;margin-top:18px}.items th{background:<?= e($cor) ?>;color:white;padding:8px;font-size:9pt;text-align:left}.items td{border-bottom:1px solid #dfe5ea;padding:8px;vertical-align:top}.right{text-align:right}.descsmall{font-size:8.7pt;color:#667886;margin-top:3px}.totalbox{width:45%;margin:15px 0 0 auto;border-collapse:collapse}.totalbox td{padding:6px;border-bottom:1px solid #dde5ea}.grand{font-size:13pt;font-weight:bold;color:<?= e($cor) ?>}.section{margin-top:18px}.section h3{color:<?= e($cor) ?>;border-bottom:1px solid #dce4ea;padding-bottom:5px}.footer-note{margin-top:26px;padding-top:10px;border-top:1px solid #dce4ea;text-align:center;color:#71808c;font-size:8.5pt}.badge{display:inline-block;border:1px solid <?= e($cor) ?>;color:<?= e($cor) ?>;padding:3px 7px;border-radius:12px;font-size:8pt}
</style></head><body>
<div class="head"><table><tr><td><?php if($logo):?><img class="logo" src="<?= e($logo) ?>"><?php else:?><strong style="font-size:20pt;color:<?= e($cor) ?>"><?= e($e['nome_empresa']??'Prodatas') ?></strong><?php endif;?></td><td class="empresa"><strong><?= e($e['razao_social']??$e['nome_empresa']??'') ?></strong><br><?= e($e['cnpj']??'') ?><br><?= e($e['endereco']??'') ?><br><?= e($e['telefone']??'') ?> · <?= e($e['email']??'') ?><br><?= e($e['site']??'') ?></td></tr></table></div>
<div class="titulo"><?= e($o['titulo']) ?></div><div class="numero">Orçamento nº <?= str_pad((string)$o['numero'],5,'0',STR_PAD_LEFT) ?> · Emitido em <?= date('d/m/Y',strtotime($o['data_emissao'])) ?> · <span class="badge"><?= e(strtoupper($o['status'])) ?></span></div>
<?php if(!empty($e['historia'])):?><div class="intro"><?= nl2br(e($e['historia'])) ?></div><?php endif;?>
<div class="box"><h3>Cliente</h3><strong><?= e($o['cliente']) ?></strong><?php if($o['documento']):?> · <?= e($o['documento']) ?><?php endif;?><br><?php if($o['contato']):?>A/C <?= e($o['contato']) ?><br><?php endif;?><?= e($o['cliente_endereco']) ?> <?= e(trim(($o['cidade']??'').' '.($o['uf']??''))) ?><br><?= e($o['cliente_telefone']) ?> <?= $o['cliente_email']?'· '.e($o['cliente_email']):'' ?></div>
<table class="items"><thead><tr><th>Descrição</th><th>Un.</th><th class="right">Qtd.</th><th class="right">Unitário</th><th class="right">Total</th></tr></thead><tbody>
<?php foreach($o['itens'] as $i):$linha=(float)$i['quantidade']*(float)$i['valor_unitario'];?><tr><td><strong><?= e($i['descricao']) ?></strong><?php if($i['detalhe']):?><div class="descsmall"><?= nl2br(e($i['detalhe'])) ?></div><?php endif;?></td><td><?= e($i['unidade']) ?></td><td class="right"><?= number_format((float)$i['quantidade'],3,',','.') ?></td><td class="right"><?= money((float)$i['valor_unitario']) ?></td><td class="right"><?= money($linha) ?></td></tr><?php endforeach;?></tbody></table>
<table class="totalbox"><tr><td>Subtotal</td><td class="right"><?= money($subtotal) ?></td></tr><?php if((float)$o['desconto']>0):?><tr><td>Desconto</td><td class="right">- <?= money((float)$o['desconto']) ?></td></tr><?php endif;?><tr class="grand"><td>Total</td><td class="right"><?= money($total) ?></td></tr></table>
<div class="section"><h3>Condições comerciais</h3><strong>Validade:</strong> até <?= $validade ?><?php if($o['prazo_entrega']):?><br><strong>Prazo:</strong> <?= e($o['prazo_entrega']) ?><?php endif;?><?php if($o['condicoes_pagamento']):?><br><strong>Pagamento:</strong> <?= nl2br(e($o['condicoes_pagamento'])) ?><?php endif;?></div>
<?php if($o['observacoes']):?><div class="section"><h3>Observações</h3><?= nl2br(e($o['observacoes'])) ?></div><?php endif;?><?php if(!empty($e['texto_rodape'])):?><div class="footer-note"><?= nl2br(e($e['texto_rodape'])) ?></div><?php endif;?>
</body></html><?php return ob_get_clean();}
